import Head from "next/head";
import Navbar from "../components/Navbar";
import { useAccount } from "wagmi";

export default function Home() {
  const isConnected = useAccount();
  return (
    <div>
      <Head>
        <title>DeCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
}
